# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

haz_func_gen <- function(shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, x, t_r, beta_l, b_il3, Ncov_l) {
    .Call('_doct_haz_func_gen', PACKAGE = 'doct', shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, x, t_r, beta_l, b_il3, Ncov_l)
}

test_haz <- function(shape, beta_s, e_y, alpha, beta_alpha, h0, ti, beta_sd, beta_sd_cum, di, tox, lambda_tox, t_r) {
    .Call('_doct_test_haz', PACKAGE = 'doct', shape, beta_s, e_y, alpha, beta_alpha, h0, ti, beta_sd, beta_sd_cum, di, tox, lambda_tox, t_r)
}

test_intensity <- function(x, mu, beta_v11, beta_v12, alpha) {
    .Call('_doct_test_intensity', PACKAGE = 'doct', x, mu, beta_v11, beta_v12, alpha)
}

integrate_intensity <- function(mu, beta_v11, beta_v12, alpha, lower, upper) {
    .Call('_doct_integrate_intensity', PACKAGE = 'doct', mu, beta_v11, beta_v12, alpha, lower, upper)
}

integrate_hazard <- function(shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, t_r, beta_l, b_il3, lower, upper, Ncov_l) {
    .Call('_doct_integrate_hazard', PACKAGE = 'doct', shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, t_r, beta_l, b_il3, lower, upper, Ncov_l)
}

loglike_surv_Rcpp <- function(shape, beta_s, beta_alpha, h0, beta_sd, beta_sd_cum, D, lambda_tox, inds_shrink_end, end_inds, EY, alphas, Ts, Toxicity, death_time, Npat, Nobs, beta_l, b_il3, Ncov_l) {
    .Call('_doct_loglike_surv_Rcpp', PACKAGE = 'doct', shape, beta_s, beta_alpha, h0, beta_sd, beta_sd_cum, D, lambda_tox, inds_shrink_end, end_inds, EY, alphas, Ts, Toxicity, death_time, Npat, Nobs, beta_l, b_il3, Ncov_l)
}

loglike_surv_i_Rcpp <- function(shape, beta_s, beta_alpha, h0, beta_sd, beta_sd_cum, D, lambda_tox, EY, alphas, Ts, Toxicity, death_time, Npat, Nobs, beta_l, b_il3, Ncov_l) {
    .Call('_doct_loglike_surv_i_Rcpp', PACKAGE = 'doct', shape, beta_s, beta_alpha, h0, beta_sd, beta_sd_cum, D, lambda_tox, EY, alphas, Ts, Toxicity, death_time, Npat, Nobs, beta_l, b_il3, Ncov_l)
}

test <- function(y, theta_a) {
    .Call('_doct_test', PACKAGE = 'doct', y, theta_a)
}

update_b_il <- function(J_cumsum, J, Npat, D, Y, Ts, curr_mean_fixed, censor, Toxicity, b_il, death_time, B, sigma2_l, curr_EY, theta_a, beta_s, shape, h0, beta_alpha, beta_sd, beta_sd_cum, lambda_tox, beta_l, k, Ncov_l) {
    .Call('_doct_update_b_il', PACKAGE = 'doct', J_cumsum, J, Npat, D, Y, Ts, curr_mean_fixed, censor, Toxicity, b_il, death_time, B, sigma2_l, curr_EY, theta_a, beta_s, shape, h0, beta_alpha, beta_sd, beta_sd_cum, lambda_tox, beta_l, k, Ncov_l)
}

CDF_intensity <- function(mu, beta_v11, beta_v12, alpha, lower, upper) {
    .Call('_doct_CDF_intensity', PACKAGE = 'doct', mu, beta_v11, beta_v12, alpha, lower, upper)
}

intensity_cdf_func <- function(upper, mu, beta_v11, beta_v12, alpha, value) {
    .Call('_doct_intensity_cdf_func', PACKAGE = 'doct', upper, mu, beta_v11, beta_v12, alpha, value)
}

CDF_hazard <- function(shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, t_r, beta_l, b_il3, lower, upper, Ncov_l) {
    .Call('_doct_CDF_hazard', PACKAGE = 'doct', shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, t_r, beta_l, b_il3, lower, upper, Ncov_l)
}

hazard_cdf_func <- function(t_r, upper, shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, beta_l, b_il3, value, Ncov_l) {
    .Call('_doct_hazard_cdf_func', PACKAGE = 'doct', t_r, upper, shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, beta_l, b_il3, value, Ncov_l)
}

cum_haz_func <- function(t_r, upper, shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, beta_l, b_il3, value, Ncov_l) {
    .Call('_doct_cum_haz_func', PACKAGE = 'doct', t_r, upper, shape, beta_s, e_y, alpha, beta_alpha, h0, beta_sd, beta_sd_cum, di, tox, lambda_tox, beta_l, b_il3, value, Ncov_l)
}

brents_fun_intensity <- function(lower, upper, tol, max_iter, mu, beta_v11, beta_v12, alpha, value) {
    .Call('_doct_brents_fun_intensity', PACKAGE = 'doct', lower, upper, tol, max_iter, mu, beta_v11, beta_v12, alpha, value)
}

brents_fun_hazard <- function(lower, upper, tol, max_iter, shape, beta_s, e_y, alpha, beta_alpha, h0, t_r, beta_sd, beta_sd_cum, di, tox, lambda_tox, beta_l, b_il3, value, Ncov_l) {
    .Call('_doct_brents_fun_hazard', PACKAGE = 'doct', lower, upper, tol, max_iter, shape, beta_s, e_y, alpha, beta_alpha, h0, t_r, beta_sd, beta_sd_cum, di, tox, lambda_tox, beta_l, b_il3, value, Ncov_l)
}

brents_fun_cum_haz <- function(lower, upper, tol, max_iter, shape, beta_s, e_y, alpha, beta_alpha, h0, t_r, beta_sd, beta_sd_cum, di, tox, lambda_tox, beta_l, b_il3, value, Ncov_l) {
    .Call('_doct_brents_fun_cum_haz', PACKAGE = 'doct', lower, upper, tol, max_iter, shape, beta_s, e_y, alpha, beta_alpha, h0, t_r, beta_sd, beta_sd_cum, di, tox, lambda_tox, beta_l, b_il3, value, Ncov_l)
}

random_visit_times_Rcpp_test <- function(mu, beta_v11, beta_v12, y_r, t_r, theta_a, k) {
    .Call('_doct_random_visit_times_Rcpp_test', PACKAGE = 'doct', mu, beta_v11, beta_v12, y_r, t_r, theta_a, k)
}

random_visit_times_Rcpp_test_fixed <- function(t_r, n_days) {
    .Call('_doct_random_visit_times_Rcpp_test_fixed', PACKAGE = 'doct', t_r, n_days)
}

toxicity_calc_RCpp <- function(d_i, t_i, t_r, lambda_tox, tox_recent) {
    .Call('_doct_toxicity_calc_RCpp', PACKAGE = 'doct', d_i, t_i, t_r, lambda_tox, tox_recent)
}

random_hazard_times_Rcpp_test_exp <- function(t_max, shape, beta_s, e_y, beta_alpha, h0, theta_a, y_r, t_r, beta_sd, beta_sd_cum, di, tox, lambda_tox, cum_haz_prev, beta_l, b_il3, Ncov_l, k) {
    .Call('_doct_random_hazard_times_Rcpp_test_exp', PACKAGE = 'doct', t_max, shape, beta_s, e_y, beta_alpha, h0, theta_a, y_r, t_r, beta_sd, beta_sd_cum, di, tox, lambda_tox, cum_haz_prev, beta_l, b_il3, Ncov_l, k)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call('_doct_mvrnormArma', PACKAGE = 'doct', n, mu, sigma)
}

mvrnormArma_single <- function(mu, sigma) {
    .Call('_doct_mvrnormArma_single', PACKAGE = 'doct', mu, sigma)
}

integrate_grad_betav2_Rcpp <- function(y_r, beta_v11, beta_v12, theta_a, k, lower, upper) {
    .Call('_doct_integrate_grad_betav2_Rcpp', PACKAGE = 'doct', y_r, beta_v11, beta_v12, theta_a, k, lower, upper)
}

function_grad_betav2_Rcpp <- function(y_r, beta_v11, beta_v12, theta_a, k, val) {
    .Call('_doct_function_grad_betav2_Rcpp', PACKAGE = 'doct', y_r, beta_v11, beta_v12, theta_a, k, val)
}

beta_v2_grad_Rcpp <- function(J_cumsum, J_cumsum_t, J, Npat, Y, Ts, beta_v11, beta_v12, mu, theta_as, ks, rewards) {
    .Call('_doct_beta_v2_grad_Rcpp', PACKAGE = 'doct', J_cumsum, J_cumsum_t, J, Npat, Y, Ts, beta_v11, beta_v12, mu, theta_as, ks, rewards)
}

integrate_grad_betav1_Rcpp <- function(y_r, beta_v11, beta_v12, theta_a, k, lower, upper) {
    .Call('_doct_integrate_grad_betav1_Rcpp', PACKAGE = 'doct', y_r, beta_v11, beta_v12, theta_a, k, lower, upper)
}

function_grad_betav1_Rcpp <- function(y_r, beta_v11, beta_v12, theta_a, k, val) {
    .Call('_doct_function_grad_betav1_Rcpp', PACKAGE = 'doct', y_r, beta_v11, beta_v12, theta_a, k, val)
}

beta_v1_grad_Rcpp <- function(J_cumsum, J_cumsum_t, J, Npat, Y, Ts, beta_v11, beta_v12, mu, theta_as, ks, rewards) {
    .Call('_doct_beta_v1_grad_Rcpp', PACKAGE = 'doct', J_cumsum, J_cumsum_t, J, Npat, Y, Ts, beta_v11, beta_v12, mu, theta_as, ks, rewards)
}

Data_Simu_Rcpp_single_pat_age_dgf <- function(beta_ls, Bs, sigma2_ls, beta_ss, beta_sds, beta_sd_cums, lambda_toxs, h0s, beta_alphas, shapes, Npat, beta_d, sigma2_ds, mu, beta_v11, beta_v12, theta_as, beta_reward, b_ils, ks, cov_in, mean_y_init, Ncov_l, Ncov_d, dosage_bounds) {
    .Call('_doct_Data_Simu_Rcpp_single_pat_age_dgf', PACKAGE = 'doct', beta_ls, Bs, sigma2_ls, beta_ss, beta_sds, beta_sd_cums, lambda_toxs, h0s, beta_alphas, shapes, Npat, beta_d, sigma2_ds, mu, beta_v11, beta_v12, theta_as, beta_reward, b_ils, ks, cov_in, mean_y_init, Ncov_l, Ncov_d, dosage_bounds)
}

Data_Simu_Rcpp_single_pat_fixed_visits <- function(beta_ls, Bs, sigma2_ls, beta_ss, beta_sds, beta_sd_cums, lambda_toxs, h0s, beta_alphas, shapes, Npat, beta_d, sigma2_ds, mu, beta_v11, beta_v12, theta_as, beta_reward, b_ils, ks, cov_in, mean_y_init, Ncov_l, Ncov_d, dosage_bounds, n_days) {
    .Call('_doct_Data_Simu_Rcpp_single_pat_fixed_visits', PACKAGE = 'doct', beta_ls, Bs, sigma2_ls, beta_ss, beta_sds, beta_sd_cums, lambda_toxs, h0s, beta_alphas, shapes, Npat, beta_d, sigma2_ds, mu, beta_v11, beta_v12, theta_as, beta_reward, b_ils, ks, cov_in, mean_y_init, Ncov_l, Ncov_d, dosage_bounds, n_days)
}

